
// Code generated by tools/gen_shims. DO NOT EDIT.

package vfstest

import "github.com/microsoft/typescript-go/internal/vfs/vfstest"
import "testing/fstest"
import _ "unsafe"

type Clock = vfstest.Clock
type MapFS = vfstest.MapFS
//go:linkname Symlink github.com/microsoft/typescript-go/internal/vfs/vfstest.Symlink
func Symlink(target string) *fstest.MapFile
