export enum CompareType {
	Equal = 'Equal',
	NotEqual = 'NotEqual',
	GreaterThan = 'GreaterThan',
	GreaterThanOrEqual = 'GreaterThanOrEqual',
	LessThan = 'LessThan',
	LessThanOrEqual = 'LessThanOrEqual',
	In = 'In',
	NotIn = 'NotIn',
	Between = 'Between',
	NotBetween = 'NotBetween',
	Like = 'Like',
	NotLike = 'NotLike',
	ILike = 'ILike',
	NotILike = 'NotILike',
	Regexp = 'Regexp',
	NotRegexp = 'NotRegexp',
	IRegexp = 'IRegexp',
	NotIRegexp = 'NotIRegexp',
	IsNull = 'IsNull',
	IsNotNull = 'IsNotNull',
}
